### ISSUE TITLE
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCTensorRandom.cu:25

### ISSUE THREAD

**Issue by dymymao** [DagnyT/hardnet#20]
when I run   python extract_hardnet_desc_from_hpatches_file.py imgs/ref.png out.txt
error occured :
--------------------------------------------------------------------------------------

> **THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorRandom.cu line=25 error=30 : unknown error
Traceback (most recent call last):
  File "extract_hardnet_desc_from_hpatches_file.py", line 90, in <module>
    checkpoint = torch.load(model_weights)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 88, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 70, in _cuda_deserialize
    return obj.cuda(device)
  File "/usr/local/lib/python2.7/dist-packages/torch/_utils.py", line 68, in _cuda
    with torch.cuda.device(device):
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 228, in __enter__
    _lazy_init()
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCTensorRandom.cu:25**

> 

------------------------------------------------------------------------------------------------------------
ubuntu16.04 + cuda8.0+cudnn5.1+pyTorch0.4.0
Thanks for help!

**Comment by DagnyT** [comment]
Please, resubmit if still valid.
