### ISSUE TITLE
Key Error occurred when running   bash run_me.sh

### ISSUE THREAD

**Issue by dandanli814** [DagnyT/hardnet#35]
0%|                                                                                               | 0/5000000 [00:00<?, ?it/s]
Traceback (most recent call last):
# Found cached data ../datasets/notredame.pt
Generating 5000000 triplets
  File "./code/HardNet.py", line 599, in <module>
    train_loader, test_loaders = create_loaders(load_random_triplets = triplet_flag)
  File "./code/HardNet.py", line 365, in create_loaders
    transform=transform),
  File "./code/HardNet.py", line 200, in __init__
    self.triplets = self.generate_triplets(self.labels, self.n_triplets)
  File "./code/HardNet.py", line 232, in generate_triplets
    if len(indices[c1]) == 2:  # hack to speed up process
KeyError: 43567

Can anyone help me? Thank you very much.

**Comment by dandanli814** [comment]
@DagnyT Can you help me solve this problem? Thank you very much.
