### ISSUE TITLE
PS model

### ISSUE THREAD

**Issue by bhack** [DagnyT/hardnet#6]
Have you tried to convert it with https://github.com/clcarwin/convert_torch_to_pytorch?

**Comment by ducha-aiki** [comment]
@bhack 

Traceback (most recent call last):
  File "convert_torch.py", line 314, in <module>
    torch_to_pytorch(args.model,args.output)
  File "convert_torch.py", line 259, in torch_to_pytorch
    model = load_lua(t7_filename,unknown_classes=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 608, in load_lua
    return reader.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 593, in read
    return self.read_object()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 593, in read
    return self.read_object()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 593, in read
    return self.read_object()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 318, in wrapper
    obj = build_fn(reader, version)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 318, in wrapper
    obj = build_fn(reader, version)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 593, in read
    return self.read_object()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 147, in read_tensor
    storage = reader.read()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 593, in read
    return self.read_object()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/serialization/read_lua_file.py", line 166, in read_storage
    return python_class.from_buffer(reader.f.read(size), 'native')
AttributeError: type object 'torch.cuda.FloatStorage' has no attribute 'from_buffer'

**Comment by bhack** [comment]
Probably is this https://github.com/clcarwin/convert_torch_to_pytorch/issues/8

**Comment by ducha-aiki** [comment]
I don`t want to install lua now :( I had it on previous Ubuntu and remember some clashed after installation lua and torch... May be @rmitra can help?

**Comment by bhack** [comment]
I think that nvidia-docker run -it kaixhin/cuda-torch is enough to have a torch env without messing the host OS.  But probably @rmitra could help in the conversion.

**Comment by ducha-aiki** [comment]
neither have a docker. I am medieval person, I know :(

**Comment by rmitra** [comment]
Hi, the link for downloading the network for PyTorch is https://www.dropbox.com/s/1p9e8vtf57gl9jc/PyTorch-hardnet-PS-CPU.pth?dl=1

Please inform me of further issues in https://github.com/rmitra/PS-Dataset.

Thanks,

**Comment by ducha-aiki** [comment]
@bhack @rmitra 
I have converted it manually. It has a bit changes in structure, than HardNet: lacking last BN layer. The structure is like this:

    class HardNetPS(nn.Module):
        def __init__(self):
            super(HardNetPS, self).__init__()
            self.features = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1, bias = True),
            nn.BatchNorm2d(32, affine=True),
            nn.ReLU(),
            nn.Conv2d(32, 32, kernel_size=3, padding=1, bias = True),
            nn.BatchNorm2d(32, affine=True),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1, bias = True),
            nn.BatchNorm2d(64, affine=True),
            nn.ReLU(),
            nn.Conv2d(64, 64, kernel_size=3, padding=1, bias = True),
            nn.BatchNorm2d(64, affine=True),
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=3, stride=2,padding=1, bias = True),
            nn.BatchNorm2d(128, affine=True),
            nn.ReLU(),
            nn.Conv2d(128, 128, kernel_size=3, padding=1, bias = True),
            nn.BatchNorm2d(128, affine=True),
            nn.ReLU(),
            nn.Conv2d(128, 128, kernel_size=8, bias = True)
        )

    def input_norm(self,x):
        flat = x.view(x.size(0), -1)
        mp = torch.mean(flat, dim=1)
        sp = torch.std(flat, dim=1) + 1e-7
        return (x - mp.unsqueeze(-1).unsqueeze(-1).unsqueeze(-1).expand_as(x)) / sp.unsqueeze(-1).unsqueeze(-1).unsqueeze(1).expand_as(x)

    def forward(self, input):
        x_features = self.features(self.input_norm(input))
        x = x_features.view(x_features.size(0), -1)
        return L2Norm()(x)`

And the converted to true PyTorch weights are here:
http://cmp.felk.cvut.cz/~mishkdmy/HardNet-PS.pth

Converted weights + code above give following performance on HPatches matching task:
HardNet-PS
    Easy      Hard     Tough      mean
--------  --------  --------  --------
0.691107  0.593172  0.460405  0.581561

vs HardNetLib+
    Easy      Hard    Tough      mean
--------  --------  -------  --------
0.696852  0.533411  0.35355  0.527938

**Comment by ducha-aiki** [comment]
I will update README.md in couple of hours with benchmark results

**Comment by ducha-aiki** [comment]
I have also asked @rmitra to compare HardNet++ (trained on Brown + HPatches) vs HardNet-PS on Fountain dataset.  I think, they should be pretty close in performance

**Comment by ducha-aiki** [comment]
Readme updated, results of HardNet-PS are in :)

**Comment by rmitra** [comment]
@ducha-aiki Thank you so much for updating the results.
